[tools]
go = "1.26.4"
buf = "1.71.0"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = { version = "1.36.11" }

[tasks.build]
description = "Build the project (includes all Go source code and proto generation)"
run = [
    "buf generate --template buf.gen.yaml protos/",
    "go fmt ./...",
    "go build ./...",
    "go vet -composites=false ./...",
]

[tasks."test:build"]
description = "Builds all testing dependencies"
dir = "{{config_root}}/internal/testdata"
depends = [
    "build"
]
run = [
    "buf generate --template buf.gen.test.yaml",
    "buf generate --template buf.protago.test.yaml"
]

[tasks.test]
description = "Run unit tests"
depends = [
    "test:build"
]
run = "go test ./..."

[tasks.testv]
description = "Run unit tests"
depends = [
    "test:build"
]
run = "go test -v ./..."
