syntax = "proto3";

package testdata;

import "protago/bson/v1/annotations.proto";
import "protago/validate/v1/annotations.proto";

option go_package = "github.com/timmonfette1/protago/internal/testdata;testdata";

message TestBson {
    string id = 1 [
        (protago.bson.v1.options) = {
            field_name: "_id"
        }
    ];
    string display_name = 2 [
        (protago.bson.v1.options) = {
            field_name: "display_name"
        }
    ];
    optional int32 age = 3 [
        (protago.bson.v1.options) = {
            field_name: "age",
            omitempty: true,
        }
    ];
    optional string kitchen_sink = 4 [
        (protago.bson.v1.options) = {
            field_name: "kitchen_sink",
            omitempty: true,
            minsize: true,
            truncate: true,
            inline: true,
        }
    ];
    optional bool skip = 5;
    optional string email = 7 [
        (protago.bson.v1.options) = {
            field_name: "email",
            omitempty: true,
        }
    ];
}

message TestValidate {
    string id = 1 [
        (protago.validate.v1.options) = {
            rule: "validate:\"required,omitempty,max=255\""
        }
    ];
    optional string email = 2 [
        (protago.validate.v1.options) = {
            rule: "validate:\"required,hostname_rfc1123\""
        }
    ];
    optional bool skip = 3;
}
