// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: validate/annotations.proto

package validate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateFieldOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Rule        *string                `protobuf:"bytes,1,opt,name=rule"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidateFieldOptions) Reset() {
	*x = ValidateFieldOptions{}
	mi := &file_validate_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFieldOptions) ProtoMessage() {}

func (x *ValidateFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_validate_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateFieldOptions) GetRule() string {
	if x != nil {
		if x.xxx_hidden_Rule != nil {
			return *x.xxx_hidden_Rule
		}
		return ""
	}
	return ""
}

func (x *ValidateFieldOptions) SetRule(v string) {
	x.xxx_hidden_Rule = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ValidateFieldOptions) HasRule() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidateFieldOptions) ClearRule() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Rule = nil
}

type ValidateFieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Rule *string
}

func (b0 ValidateFieldOptions_builder) Build() *ValidateFieldOptions {
	m0 := &ValidateFieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Rule != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Rule = b.Rule
	}
	return m0
}

var file_validate_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ValidateFieldOptions)(nil),
		Field:         80000081,
		Name:          "github.timmonfette1.protago.validate.options",
		Tag:           "bytes,80000081,opt,name=options",
		Filename:      "validate/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional github.timmonfette1.protago.validate.ValidateFieldOptions options = 80000081;
	E_Options = &file_validate_annotations_proto_extTypes[0]
)

var File_validate_annotations_proto protoreflect.FileDescriptor

const file_validate_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1avalidate/annotations.proto\x12$github.timmonfette1.protago.validate\x1a google/protobuf/descriptor.proto\"*\n" +
	"\x14ValidateFieldOptions\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule:v\n" +
	"\aoptions\x12\x1d.google.protobuf.FieldOptions\x18\xd1\xe8\x92& \x01(\v2:.github.timmonfette1.protago.validate.ValidateFieldOptionsR\aoptionsBEZCgithub.com/timmonfette1/protago/internal/genproto/validate;validateb\beditionsp\xe9\a"

var file_validate_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validate_annotations_proto_goTypes = []any{
	(*ValidateFieldOptions)(nil),      // 0: github.timmonfette1.protago.validate.ValidateFieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_validate_annotations_proto_depIdxs = []int32{
	1, // 0: github.timmonfette1.protago.validate.options:extendee -> google.protobuf.FieldOptions
	0, // 1: github.timmonfette1.protago.validate.options:type_name -> github.timmonfette1.protago.validate.ValidateFieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_annotations_proto_init() }
func file_validate_annotations_proto_init() {
	if File_validate_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_annotations_proto_rawDesc), len(file_validate_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_validate_annotations_proto_goTypes,
		DependencyIndexes: file_validate_annotations_proto_depIdxs,
		MessageInfos:      file_validate_annotations_proto_msgTypes,
		ExtensionInfos:    file_validate_annotations_proto_extTypes,
	}.Build()
	File_validate_annotations_proto = out.File
	file_validate_annotations_proto_goTypes = nil
	file_validate_annotations_proto_depIdxs = nil
}
