// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bson/annotations.proto

package bson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BsonFieldOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FieldName   *string                `protobuf:"bytes,1,opt,name=field_name,json=fieldName"`
	xxx_hidden_OmitEmpty   bool                   `protobuf:"varint,2,opt,name=omit_empty,json=omitEmpty"`
	xxx_hidden_Minsize     bool                   `protobuf:"varint,3,opt,name=minsize"`
	xxx_hidden_Truncate    bool                   `protobuf:"varint,4,opt,name=truncate"`
	xxx_hidden_Inline      bool                   `protobuf:"varint,5,opt,name=inline"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BsonFieldOptions) Reset() {
	*x = BsonFieldOptions{}
	mi := &file_bson_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BsonFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BsonFieldOptions) ProtoMessage() {}

func (x *BsonFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bson_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BsonFieldOptions) GetFieldName() string {
	if x != nil {
		if x.xxx_hidden_FieldName != nil {
			return *x.xxx_hidden_FieldName
		}
		return ""
	}
	return ""
}

func (x *BsonFieldOptions) GetOmitEmpty() bool {
	if x != nil {
		return x.xxx_hidden_OmitEmpty
	}
	return false
}

func (x *BsonFieldOptions) GetMinsize() bool {
	if x != nil {
		return x.xxx_hidden_Minsize
	}
	return false
}

func (x *BsonFieldOptions) GetTruncate() bool {
	if x != nil {
		return x.xxx_hidden_Truncate
	}
	return false
}

func (x *BsonFieldOptions) GetInline() bool {
	if x != nil {
		return x.xxx_hidden_Inline
	}
	return false
}

func (x *BsonFieldOptions) SetFieldName(v string) {
	x.xxx_hidden_FieldName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *BsonFieldOptions) SetOmitEmpty(v bool) {
	x.xxx_hidden_OmitEmpty = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *BsonFieldOptions) SetMinsize(v bool) {
	x.xxx_hidden_Minsize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *BsonFieldOptions) SetTruncate(v bool) {
	x.xxx_hidden_Truncate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *BsonFieldOptions) SetInline(v bool) {
	x.xxx_hidden_Inline = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *BsonFieldOptions) HasFieldName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BsonFieldOptions) HasOmitEmpty() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BsonFieldOptions) HasMinsize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BsonFieldOptions) HasTruncate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BsonFieldOptions) HasInline() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BsonFieldOptions) ClearFieldName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FieldName = nil
}

func (x *BsonFieldOptions) ClearOmitEmpty() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OmitEmpty = false
}

func (x *BsonFieldOptions) ClearMinsize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Minsize = false
}

func (x *BsonFieldOptions) ClearTruncate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Truncate = false
}

func (x *BsonFieldOptions) ClearInline() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Inline = false
}

type BsonFieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FieldName *string
	OmitEmpty *bool
	Minsize   *bool
	Truncate  *bool
	Inline    *bool
}

func (b0 BsonFieldOptions_builder) Build() *BsonFieldOptions {
	m0 := &BsonFieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FieldName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_FieldName = b.FieldName
	}
	if b.OmitEmpty != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_OmitEmpty = *b.OmitEmpty
	}
	if b.Minsize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Minsize = *b.Minsize
	}
	if b.Truncate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Truncate = *b.Truncate
	}
	if b.Inline != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Inline = *b.Inline
	}
	return m0
}

var file_bson_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*BsonFieldOptions)(nil),
		Field:         80000080,
		Name:          "github.timmonfette1.protago.bson.options",
		Tag:           "bytes,80000080,opt,name=options",
		Filename:      "bson/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional github.timmonfette1.protago.bson.BsonFieldOptions options = 80000080;
	E_Options = &file_bson_annotations_proto_extTypes[0]
)

var File_bson_annotations_proto protoreflect.FileDescriptor

const file_bson_annotations_proto_rawDesc = "" +
	"\n" +
	"\x16bson/annotations.proto\x12 github.timmonfette1.protago.bson\x1a google/protobuf/descriptor.proto\"\x9e\x01\n" +
	"\x10BsonFieldOptions\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"omit_empty\x18\x02 \x01(\bR\tomitEmpty\x12\x18\n" +
	"\aminsize\x18\x03 \x01(\bR\aminsize\x12\x1a\n" +
	"\btruncate\x18\x04 \x01(\bR\btruncate\x12\x16\n" +
	"\x06inline\x18\x05 \x01(\bR\x06inline:n\n" +
	"\aoptions\x12\x1d.google.protobuf.FieldOptions\x18\xd0\xe8\x92& \x01(\v22.github.timmonfette1.protago.bson.BsonFieldOptionsR\aoptionsB=Z;github.com/timmonfette1/protago/internal/genproto/bson;bsonb\beditionsp\xe9\a"

var file_bson_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bson_annotations_proto_goTypes = []any{
	(*BsonFieldOptions)(nil),          // 0: github.timmonfette1.protago.bson.BsonFieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_bson_annotations_proto_depIdxs = []int32{
	1, // 0: github.timmonfette1.protago.bson.options:extendee -> google.protobuf.FieldOptions
	0, // 1: github.timmonfette1.protago.bson.options:type_name -> github.timmonfette1.protago.bson.BsonFieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bson_annotations_proto_init() }
func file_bson_annotations_proto_init() {
	if File_bson_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bson_annotations_proto_rawDesc), len(file_bson_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_bson_annotations_proto_goTypes,
		DependencyIndexes: file_bson_annotations_proto_depIdxs,
		MessageInfos:      file_bson_annotations_proto_msgTypes,
		ExtensionInfos:    file_bson_annotations_proto_extTypes,
	}.Build()
	File_bson_annotations_proto = out.File
	file_bson_annotations_proto_goTypes = nil
	file_bson_annotations_proto_depIdxs = nil
}
